In [1]:
import pandas as pd

from contextlib import closing
from pathlib import Path

from dsi.dsi import DSI
from dsi.sync import Sync

from dsi.dsifederated import DSIFederated

In [2]:
help(DSI)

Help on class DSI in module dsi.dsi:

class DSI(builtins.object)
 |  DSI(filename='.temp_dsi.db', backend_name='Sqlite', **kwargs)
 |
 |  A user-facing interface for DSI's Core middleware.
 |
 |  The DSI Class abstracts Core.Terminal for managing metadata and Core.Sync for data management and movement.
 |
 |  Methods defined here:
 |
 |  __init__(self, filename='.temp_dsi.db', backend_name='Sqlite', **kwargs)
 |      Initializes DSI by activating a backend for data operations; default is a Sqlite backend for temporary data analysis.
 |      If users specify `filename`, data is saved to a permanent backend file.
 |
 |      `filename` : str, optional, default is ".temp_dsi.db"
 |          If not specified, a temporary, hidden backend file is created for users to analyze their data.
 |          If specified and backend file already exists, it is activated for a user to explore its data.
 |          If specified and backend file does not exist, a file with this name is created.
 |
 |          Accepted file extensions for DSI-compatible backends:
 |              - If backend_name = "Sqlite" → .db, .sqlite, .sqlite3
 |              - If backend_name = "DuckDB" → .duckdb, .db
 |
 |      `backend_name` : str, optional, default is "Sqlite".
 |          Name of the backend to activate.
 |
 |          If using a DSI-supported backend, must be either "Sqlite", "DuckDB".
 |
 |          If using an external backend, provide the relative path to the Python module with the backend.
 |
 |  close(self)
 |      Closes the connection to the active backend and clears all loaded DSI modules.
 |
 |  display(self, table_name, num_rows=25, display_cols=None)
 |      Prints data from a specified table in the active backend.
 |
 |      `table_name` : str
 |          Name of the table to display.
 |
 |      `num_rows` : int, optional, default=25
 |          Maximum number of rows to print. If the table contains fewer rows, only those are shown.
 |
 |      `display_cols` : list of str, optional
 |          List of specific column names to display from the table.
 |
 |          If None (default), all columns are displayed.
 |
 |  fetch(self, fname)
 |
 |  find(self, query, collection=False, update=False)
 |      Finds all rows in the table where a column-level condition (e.g., "age > 4") is satisfied.
 |
 |      `query` : str
 |          A column-level condition that must be in the format of a [column name] [operator] [value].
 |          The value can be a string or number. Valid operators as example queries:
 |
 |          - age > 4
 |          - age < 4
 |          - age >= 4
 |          - age <= 4
 |          - age = 4
 |          - age == 4
 |          - age ~ 4    --> column age contains the number 4
 |          - age ~~ 4   --> column age contains the number 4
 |          - age != 4
 |          - age (4, 8) --> all values in 'age' between 4 and 8 (inclusive)
 |
 |      `collection` : bool, optional, default False.
 |          If True, returns a pandas DataFrame representing a subset of table rows that satisfy the `query`.
 |
 |          If False (default), prints the result.
 |
 |      `update` : bool, optional, default False.
 |          If True, includes 'dsi_table_name' and 'dsi_row_index' columns required for ``dsi.update()``.
 |
 |          If False (default), return object does not include these columns.
 |
 |      `return` : If there are no matches found, then nothing is returned or printed
 |
 |  get(self, dbname=None)
 |      #help, edge-finding (find this/that)
 |
 |  get_table(self, table_name, collection=False, update=False)
 |      Retrieves all data from a specified table without requiring knowledge of the active backend's query language.
 |
 |      This method offers a simplified alternative to `query()` for retrieving a full table data without using SQL.
 |
 |      `table_name` : str
 |          Name of the table from which all data will be retrieved.
 |
 |      `collection` : bool, optional, default False.
 |          If True, returns the result as a pandas DataFrame.
 |
 |          If False (default), prints the result.
 |
 |      `update` : bool, optional, default False.
 |          If True, includes a 'dsi_table_name' column required for ``dsi.update()``.
 |
 |          If False (default), return object does not include this column.
 |
 |      `return`: If `table_name` does not exist in the backend, then nothing is returned or printed
 |
 |  list(self, collection: bool = False) -> list | None
 |      Gets the names and dimensions (rows x columns) of all tables in the active backend.
 |
 |      Arguments:
 |          collection (bool): If True, returns a Python list of all the table names else if False (default), prints each table's name and dimensions to the console.
 |
 |      Returns:
 |          list | None : list of table names if collection is True, else None. If there are no tables in the backend, then nothing is returned or printed.
 |
 |      Raises:
 |          ValueError: If backend is empty or invalid.
 |          RuntimeError: If called before schema data is loaded or if listing fails.
 |
 |  list_backends(self)
 |      Prints a list of valid backends that can be used in the `backend_name` argument in `backend()`
 |
 |  list_readers(self)
 |      Prints a list of valid readers that can be used in the `reader_name` argument in `read()`
 |
 |  list_writers(self)
 |      Prints a list of valid writers that can be used in the `writer_name` argument in `write()`
 |
 |  move(self, filepath)
 |
 |  num_tables(self)
 |      Prints the number of tables in the active backend.
 |
 |  query(self, statement, collection=False, update=False)
 |      Executes a SQL query on the active backend.
 |
 |      `statement` : str
 |          A SQL query to execute. Only `SELECT` and `PRAGMA` statements are allowed.
 |
 |      `collection` : bool, optional, default False.
 |          If True, returns the result as a pandas DataFrame.
 |
 |          If False (default), prints the result.
 |
 |      `update` : bool, optional, default False.
 |          If True, includes a 'dsi_table_name' column required for ``dsi.update()``.
 |
 |          If False (default), return object does not include this column.
 |
 |      `return`: If the `statement` is incorrectly formatted, then nothing is returned or printed
 |
 |  read(self, data_sources: str | list[str] | dict | pandas.core.frame.DataFrame | None = None, reader_name: str | None = None, table_name=None, **kwargs)
 |      Loads data into DSI using the specified parameter `reader_name`
 |
 |      `data_sources` : str, list of str, or data object (dict or pandas DataFrame)
 |          File path(s) to the data, or an in-memory data object.
 |
 |          The expected input type depends on the selected `reader_name` (if a DSI-supported Reader):
 |              - "Collection"           → python dictionary, OrderedDict, or pandas DataFrame
 |              - "CSV"                  → .csv
 |              - "Parquet"              → .pq
 |              - "YAML"                 → .yaml or .yml
 |              - "YAML1"                → .yaml or .yml
 |              - "TOML"                 → .toml
 |              - "TOML1"                → .toml
 |              - "JSON"                 → .json
 |              - "Ensemble"             → .csv
 |              - "Cloverleaf"           → /path/to/data/directory/
 |              - "Bueno"                → .data
 |              - "DublinCoreDatacard"   → .xml
 |              - "SchemaOrgDatacard"    → .json
 |              - "GoogleDatacard"       → .yaml or .yml
 |              - "Oceans11Datacard"     → .yaml or .yml
 |              - "GenesisDatacard"      → .md
 |
 |      `reader_name` : str
 |          Name of the DSI Reader to use for loading the data.
 |
 |          If using a DSI-supported Reader, this should be one of the reader_names from `list_readers()`.
 |
 |          If using a custom Reader, provide the relative file path to the Python script with the Reader.
 |          For guidance on creating a DSI-compatible Reader, view :ref:`custom_reader`.
 |
 |      `table_name` : str, optional
 |          Name to assign to the loaded table.
 |
 |          Required when using the `Collection` reader to load an dictionary or pandas DataFrame representing only one table.
 |
 |          Recommended when the input file contains a single table for the `CSV`, `Parquet`, `JSON`, or `Ensemble` reader.
 |
 |  schema(self, filename=None)
 |      Either loads a relational database schema into DSI with a specified `filename` OR returns this database's structural schema.
 |
 |      `filename` : str, optional
 |          Path to a JSON file describing the relationships of the tables in a database.
 |          The schema should follow the format described in :ref:`user_schema_example_label`
 |
 |      `return` : If filename = None, returns the structural schema of this database - table/col names and their units.
 |      **If loading a relational schema, this function must be called before reading in any associated data files**
 |
 |  search(self, query, collection=False)
 |      Finds all rows across all tables in the active backend where `query` can be found.
 |
 |      `query` : int, float, or str
 |          The value to search for in all rows across all tables.
 |
 |      `collection` : bool, optional, default False.
 |          If True, returns a list of pandas DataFrames representing a subset of tables where `query` is found.
 |
 |          If False (default), prints the matches to the console.
 |
 |  summary(self, table_name=None, collection=False)
 |      Prints numerical metadata and (optionally) sample data from tables in the active backend.
 |
 |      `table_name` : str, optional
 |          If specified, only the numerical metadata for that table will be printed.
 |
 |          If None (default), metadata for all available tables is printed.
 |
 |      `collection` : bool, optional, default False.
 |          If True, and table_name specified, returns a Pandas DataFrame of the summary of that table.
 |
 |          If True, and table_name not specified, returns a list of Pandas DataFrames of the summary of all tables.
 |
 |          If False (default), prints each table's name and dimensions to the console.
 |
 |  update(self, collection, backup=False)
 |      Updates data in one or more tables in the active backend using the provided input.
 |      Intended to be used after modifying the output of `find()`, `search()`, `query()`, or `get_table()`
 |
 |      `collection` : pandas.DataFrame
 |          The data used to update a table.
 |          DataFrame must include unchanged **`dsi_`** columns from `find()`, `search()`, `query()` or `get_table()` to successfully update.
 |
 |          - If a `query()` DataFrame is the input, the corresponding table in the backend will be completely overwritten.
 |
 |      `backup` : bool, optional, default False.
 |          If True, creates a backup file for the DSI backend before updating its data.
 |
 |          If False (default), only updates the data.
 |
 |      - NOTE: Columns from the original table cannot be deleted during update. Only row edits or column additions are allowed.
 |      - NOTE: If update() affects a user-defined primary key column, row order may change upon reinsertion.
 |
 |  write(self, filename, writer_name, table_name=None, **kwargs)
 |      Exports data from the active backend using the specified `writer_name`.
 |
 |      `filename` : str
 |          Name of the output file to write.
 |
 |          Expected file extensions based on `writer_name` (if a DSI-supported Writer):
 |              - "ER_Diagram"   → .png, .pdf, .jpg, .jpeg
 |              - "Table_Plot"   → .png, .jpg, .jpeg
 |              - "Csv"          → .csv
 |              - "Parquet"      → .pq
 |
 |      `writer_name` : str
 |          Name of the DSI Writer to export data.
 |
 |          If using a DSI-supported Writer, this should be one of the writer_names from `list_writers()`.
 |
 |          If using a custom Writer, provide the relative file path to the Python script with the Writer.
 |          For guidance on creating a DSI-compatible Writer, view :ref:`custom_writer`.
 |
 |      `table_name`: str, optional
 |          Required when using "Table_Plot", "Csv" or "Parquet" to specify which table to export.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  __dict__
 |      dictionary for instance variables
 |
 |  __weakref__
 |      list of weak references to the object

In [3]:
help(DSIFederated)

Help on class DSIFederated in module dsi.dsifederated:

class DSIFederated(builtins.object)
 |  DSIFederated(federated_folder_path: str, operating_mode: str = 'console')
 |
 |  A class for federated querying of DSI databases. It loads metadata about the databases and
 |  their tables from a specified folder, and provides methods to summarize, query, search, and find data across the federated databases.
 |
 |  Methods defined here:
 |
 |  __init__(self, federated_folder_path: str, operating_mode: str = 'console')
 |      Initializes the DSIFederated class by loading metadata about the federated databases and their tables from a specified folder.
 |
 |      Args:
 |          federated_folder_path (str): The file path to the folder containing the metadata about the federated databases. The folder should contain a JSON file named "dsi_database_list.json" with the metadata information.
 |          operating_mode (str): console or notebook, determines how the results are displayed. Default is "console".
 |
 |  f_display_databases(self) -> None
 |      Prints a DataFrame containing information about the federated databases, including their paths, names, and tables.
 |
 |  f_federate(self, config_file: str, workspace_folder: str = '')
 |      Federates databases based on a specified configuration file containing the criteria for federating the databases.
 |
 |      Args:
 |          config_path (str): The file path to the configuration file containing the criteria for federating the databases. The configuration file should be in JSON format and contain the necessary information for federating the databases.
 |
 |  f_find(self, query: str, db: str, table: str = '')
 |      Finds a specified query in a specified database within the federated system.
 |
 |      Args:
 |          table (str): The name of the table to find.
 |          db (str): The name of the database containing the table.
 |          query (str): The query to find in the specified table.
 |
 |      Returns:
 |          The result of the find operation.
 |
 |  f_get_databases(self) -> list[dict]
 |      Returns a list of dictionaries containing information about the federated databases, including their paths, names, and tables.
 |
 |      Returns:
 |          list[dict]: A list of dictionaries, where each dictionary contains information about a federated database, including its path, name, original location, and tables.
 |
 |  f_query(self, query: str, db: str, table: str = '')
 |      Executes a query on a specified table in a specified database within the federated system.
 |
 |      Args:
 |          query (str): The query to execute on the specified table.
 |          db (str): The name of the database containing the table.
 |          table (str): The name of the table to query.
 |
 |      Returns:
 |          The result of the query execution.
 |
 |  f_search(self, query: str, db: str, table: str = '')
 |      Searches for a specified query in a specified table in a specified database within the federated system.
 |
 |      Args:
 |          table (str): The name of the table to search.
 |          db (str): The name of the database containing the table.
 |          query (str): The query to search for in the specified table.
 |
 |  f_search_for_databases(self, name: str | None = None, original_location: str | None = None, return_output=False) -> dict | None
 |      Searches for databases in the federated system based on specified criteria such as name and original location.
 |
 |      Args:
 |          name (str | None): A string to search for in the database names. If None, this criterion is ignored. Default is None.
 |          original_location (str | None): A string to search for in the original location of the databases. If None, this criterion is ignored. Default is None.
 |          return_output (bool): Whether to return the output as a dictionary. Default is False.
 |
 |  f_summary(self, db: str, table: str = '')
 |      Summarizes the contents in a specified database and a database if provided within the federated system.
 |
 |      Args:
 |          table (str): The name of the table to summarize.
 |          db (str): The name of the database containing the table.
 |
 |      Returns:
 |          The summary of the specified table.
 |
 |  get_db_path(self, db_name: str) -> list[str]
 |      Returns a list of file paths for databases with the specified name within the federated system.
 |
 |      Args:
 |          db_name (str): The name of the database to find.
 |
 |      Returns:
 |          list[str]: A list of file paths for databases with the specified name.
 |
 |  init_federated(self, dsi_databases_list: list[dict])
 |      Initializes the federated system by loading metadata about the federated databases and their tables from a specified folder.
 |        This method is called during the initialization of the DSIFederated class.
 |
 |      Args:
 |          dsi_databases_list (list[dict]): A list of dictionaries containing information about each federated database.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  __dict__
 |      dictionary for instance variables
 |
 |  __weakref__
 |      list of weak references to the object

In [4]:
config_file = "input.yaml"

In [5]:
workspace_folder = "/home/pascalgrosset/projects/dsi/pascal_data_01"

In [6]:
federated_dbs = DSIFederated(workspace_folder, operating_mode="notebook")

In [7]:
#federated_dbs.f_federate(config_file=config_file, workspace_folder=workspace_folder)

In [8]:
federated_dbs._list_databases()

,id,original_location,original_path,name,path,num_tables,tables
0,nonchalant-alligator,local,/home/pascalgrosset/projects/dsi/examples/fede...,ocean_11_datasets.db,/home/pascalgrosset/projects/dsi/examples/fede...,1,[genesis_datacard]
1,accelerated-tench,url,https://www.timestored.com/data/sample/sakila.db,sakila.db,/home/pascalgrosset/projects/dsi/pascal_data_0...,16,"[actor, country, city, address, language, cate..."
2,authentic-markhor,github,https://github.com/lanl/dsi/tree/ai_dev/tools/...,ocean_11_datasets.db,/home/pascalgrosset/projects/dsi/pascal_data_0...,1,[genesis_datacard]
3,intelligent-roadrunner,darwin-fe.lanl.gov,/vast/projects/exasky/pascal/genesis_model_car...,modelcard.db,/home/pascalgrosset/projects/dsi/pascal_data_0...,1,[models]

In [9]:
tbls = federated_dbs._list_tables()

In [10]:
tbls

,id,original_location,original_path,name,path,num_tables,table
0,nonchalant-alligator,local,/home/pascalgrosset/projects/dsi/examples/fede...,ocean_11_datasets.db,/home/pascalgrosset/projects/dsi/examples/fede...,1,genesis_datacard
1,accelerated-tench,url,https://www.timestored.com/data/sample/sakila.db,sakila.db,/home/pascalgrosset/projects/dsi/pascal_data_0...,16,actor
1,accelerated-tench,url,https://www.timestored.com/data/sample/sakila.db,sakila.db,/home/pascalgrosset/projects/dsi/pascal_data_0...,16,country
1,accelerated-tench,url,https://www.timestored.com/data/sample/sakila.db,sakila.db,/home/pascalgrosset/projects/dsi/pascal_data_0...,16,city
1,accelerated-tench,url,https://www.timestored.com/data/sample/sakila.db,sakila.db,/home/pascalgrosset/projects/dsi/pascal_data_0...,16,address
1,accelerated-tench,url,https://www.timestored.com/data/sample/sakila.db,sakila.db,/home/pascalgrosset/projects/dsi/pascal_data_0...,16,language
1,accelerated-tench,url,https://www.timestored.com/data/sample/sakila.db,sakila.db,/home/pascalgrosset/projects/dsi/pascal_data_0...,16,category
1,accelerated-tench,url,https://www.timestored.com/data/sample/sakila.db,sakila.db,/home/pascalgrosset/projects/dsi/pascal_data_0...,16,customer
1,accelerated-tench,url,https://www.timestored.com/data/sample/sakila.db,sakila.db,/home/pascalgrosset/projects/dsi/pascal_data_0...,16,film
1,accelerated-tench,url,https://www.timestored.com/data/sample/sakila.db,sakila.db,/home/pascalgrosset/projects/dsi/pascal_data_0...,16,film_actor
1,accelerated-tench,url,https://www.timestored.com/data/sample/sakila.db,sakila.db,/home/pascalgrosset/projects/dsi/pascal_data_0...,16,film_category
1,accelerated-tench,url,https://www.timestored.com/data/sample/sakila.db,sakila.db,/home/pascalgrosset/projects/dsi/pascal_data_0...,16,film_text
1,accelerated-tench,url,https://www.timestored.com/data/sample/sakila.db,sakila.db,/home/pascalgrosset/projects/dsi/pascal_data_0...,16,inventory
1,accelerated-tench,url,https://www.timestored.com/data/sample/sakila.db,sakila.db,/home/pascalgrosset/projects/dsi/pascal_data_0...,16,staff
1,accelerated-tench,url,https://www.timestored.com/data/sample/sakila.db,sakila.db,/home/pascalgrosset/projects/dsi/pascal_data_0...,16,store
1,accelerated-tench,url,https://www.timestored.com/data/sample/sakila.db,sakila.db,/home/pascalgrosset/projects/dsi/pascal_data_0...,16,payment
1,accelerated-tench,url,https://www.timestored.com/data/sample/sakila.db,sakila.db,/home/pascalgrosset/projects/dsi/pascal_data_0...,16,rental
2,authentic-markhor,github,https://github.com/lanl/dsi/tree/ai_dev/tools/...,ocean_11_datasets.db,/home/pascalgrosset/projects/dsi/pascal_data_0...,1,genesis_datacard
3,intelligent-roadrunner,darwin-fe.lanl.gov,/vast/projects/exasky/pascal/genesis_model_car...,modelcard.db,/home/pascalgrosset/projects/dsi/pascal_data_0...,1,models

In [11]:
federated_dbs.f_search_for_databases(original_location="darwin")

,id,original_location,original_path,name,path,num_tables,tables
3,intelligent-roadrunner,darwin-fe.lanl.gov,/vast/projects/exasky/pascal/genesis_model_car...,modelcard.db,/home/pascalgrosset/projects/dsi/pascal_data_0...,1,[models]

In [12]:
federated_dbs.f_search_for_databases(name="ocean_11_datasets")

,id,original_location,original_path,name,path,num_tables,tables
0,nonchalant-alligator,local,/home/pascalgrosset/projects/dsi/examples/fede...,ocean_11_datasets.db,/home/pascalgrosset/projects/dsi/examples/fede...,1,[genesis_datacard]
2,authentic-markhor,github,https://github.com/lanl/dsi/tree/ai_dev/tools/...,ocean_11_datasets.db,/home/pascalgrosset/projects/dsi/pascal_data_0...,1,[genesis_datacard]

In [ ]:
federated_dbs.f_summary(db="ocean_11_datasets.db")

In [ ]:
#federated_dbs.f_find(query="dens_max > 5", db="nif.db")

In [ ]:
# Get the path to the data
x = federated_dbs._find_db_path(db="ocean_11_datasets.db")

In [ ]:
x

In [ ]:
db_1 = "/home/pascalgrosset/projects/dsi/examples/test_data_s/data_part_1.db"
db_2 = "/home/pascalgrosset/projects/dsi/examples/test_data_s/data_part_2.db"
db_3 = "/home/pascalgrosset/projects/dsi/examples/test_data_s/data_part_3.db"

In [ ]:
dsi_db_a = DSI(filename=db_1, backend_name="sqlite")
dsi_db_b = DSI(filename=db_2, backend_name="sqlite")
dsi_db_c = DSI(filename=db_3, backend_name="sqlite")

In [ ]:
df_db_a =  dsi_db_a.get_table(table_name="data", collection=True)
df_db_b =  dsi_db_b.get_table(table_name="data", collection=True)
df_db_c =  dsi_db_c.get_table(table_name="data_x", collection=True)

In [ ]:
df_db_b

In [ ]:
merged = pd.merge(df_db_a, df_db_b, on='id', how='outer')

In [ ]:
merged

In [ ]:
merged1 = pd.merge(df_db_a, df_db_c, on='id', how='outer')

In [ ]:
merged1

In [ ]:
df_db_a

In [ ]:
df_db_c

In [ ]:
def merge_tables(

In [ ]:
def merge_tables(entries: list[dict]) -> dict:
    for entry in entries:
        print(f"Processing id={entry['id']}, db={entry['db']}, table={entry['table']}")