In [ ]:
import pandas as pd

from contextlib import closing
from pathlib import Path

from dsi.dsi import DSI

from dsi.utils.dsi_utils import f_dsi

In [ ]:
help(DSI)

In [ ]:
help(f_dsi)

# First pull
```bash
(venv_dsi) pascalgrosset@PN2608148:~/projects/dsi$ python tools/federated/federate_dataset.py tools/federated/input.yaml
Databases will be synchronized to: dsi_databases_1
Created: /home/pascalgrosset/projects/dsi/dsi_databases_1
host_usernames.json does not exist. We will create a new one.

 - Processing database at github:github:https://github.com/lanl/dsi/tree/ai_dev/tools/ai_search/data/oceans_11/ocean_11_datasets.db

 - Processing database at HPC:darwin-fe.lanl.gov:/users/pulido/modelcard2.db
 -- Enter the username for darwin-fe.lanl.gov: pascalgrosset
 -- Could not access the file at darwin-fe.lanl.gov:/users/pulido/modelcard2.db. Skipping this database.

 - Processing database at HPC:ch-fe.lanl.gov:/lustre/scratch5/pascalgrosset/test_db/nif.db
 -- Enter the username for ch-fe.lanl.gov: pascalgrosset
(pascalgrosset@ch-fe.lanl.gov) Password:
(pascalgrosset@ch-fe.lanl.gov) Password:
 -- Interrupted while checking ch-fe.lanl.gov:/lustre/scratch5/pascalgrosset/test_db/nif.db. Skipping this database.

 - Processing database at HPC:darwin-fe.lanl.gov:/vast/projects/exasky/pascal/genesis_model_cards/modelcard.db
      1,093,632 100%    4.38MB/s    0:00:00 (xfr#1, to-chk=0/1)

Finished gathering databases. Successfully downloaded 2 databases to dsi_databases_1.
```


# Second pull
```bash
(venv_dsi) pascalgrosset@PN2608148:~/projects/dsi$ python tools/federated/federate_dataset.py tools/federated/input.yaml
Databases will be synchronized to: dsi_databases_1
Created: /home/pascalgrosset/projects/dsi/dsi_databases_1

 - Processing database at github:github:https://github.com/lanl/dsi/tree/ai_dev/tools/ai_search/data/oceans_11/ocean_11_datasets.db

 - Processing database at HPC:darwin-fe.lanl.gov:/users/pulido/modelcard2.db
 -- Could not access the file at darwin-fe.lanl.gov:/users/pulido/modelcard2.db. Skipping this database.

 - Processing database at HPC:ch-fe.lanl.gov:/lustre/scratch5/pascalgrosset/test_db/nif.db
(pascalgrosset@ch-fe.lanl.gov) Password:
(pascalgrosset@ch-fe.lanl.gov) Password:
 -- Interrupted while checking ch-fe.lanl.gov:/lustre/scratch5/pascalgrosset/test_db/nif.db. Skipping this database.

 - Processing database at HPC:darwin-fe.lanl.gov:/vast/projects/exasky/pascal/genesis_model_cards/modelcard.db
 -- Local file is up to date with the remote file. Skipping download.

 - Processing database at HPC:saul.nersc.gov:/global/u1/p/pascal/duckdb-demo.duckdb
 -- Enter the username for saul.nersc.gov: pascal
(pascal@saul.nersc.gov) Password + OTP:
(pascal@saul.nersc.gov) Password + OTP:
(pascal@saul.nersc.gov) Password + OTP:
***************************************************************************
                          NOTICE TO USERS

Lawrence Berkeley National Laboratory operates this computer system under
contract to the U.S. Department of Energy.  This computer system is the
property of the United States Government and is for authorized use only.
Users (authorized or unauthorized) have no explicit or implicit
expectation of privacy.

Any or all uses of this system and all files on this system may be
intercepted, monitored, recorded, copied, audited, inspected, and disclosed
to authorized site, Department of Energy, and law enforcement personnel,
as well as authorized officials of other agencies, both domestic and foreign.
By using this system, the user consents to such interception, monitoring,
recording, copying, auditing, inspection, and disclosure at the discretion
of authorized site or Department of Energy personnel.

Unauthorized or improper use of this system may result in administrative
disciplinary action and civil and criminal penalties. By continuing to use
this system you indicate your awareness of and consent to these terms and
conditions of use. LOG OFF IMMEDIATELY if you do not agree to the conditions
stated in this warning.

*****************************************************************************

Login connection to host x3116c0s21b0n0:

(pascal@saul.nersc.gov) Password + OTP:
Lmod has detected the following error: The following module(s) are unknown:
"tmux"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore_cache load "tmux"

Also make sure that all modulefiles written in TCL start with the string
#%Module



      4,993,024 100%    3.37MB/s    0:00:01 (xfr#1, to-chk=0/1)

Finished gathering databases. Successfully downloaded 2 databases to dsi_databases_1.
```

In [2]:
workspace_folder = "/home/pascalgrosset/projects/dsi/dsi_databases_001_05/"

In [3]:
federated_dbs = f_dsi(workspace_folder, operating_mode="notebook")

In [4]:
federated_dbs.f_display_databases()

,id,original_location,original_path,name,path,num_tables,tables
0,0,ch-fe.lanl.gov,/lustre/scratch5/pascalgrosset/test_db/nif.db,nif.db,/home/pascalgrosset/projects/dsi/dsi_databases...,2,"[array_and_types, nif_metadata]"
1,1,local,/home/pascalgrosset/data/artimis/fracture/3d/a...,fracture_aleks.sqlite,/home/pascalgrosset/data/artimis/fracture/3d/a...,10,"[data_file, data_file_stats, frac_graph, frac_..."
2,2,local,/home/pascalgrosset/projects/dsi/tools/federat...,ocean_11_datasets.db,/home/pascalgrosset/projects/dsi/tools/federat...,1,[genesis_datacard]
3,3,url,https://www.timestored.com/data/sample/sakila.db,sakila.db,/home/pascalgrosset/projects/dsi/dsi_databases...,16,"[actor, country, city, address, language, cate..."
4,4,github,https://github.com/lanl/dsi/tree/ai_dev/tools/...,ocean_11_datasets.db,/home/pascalgrosset/projects/dsi/dsi_databases...,1,[genesis_datacard]
5,5,darwin-fe.lanl.gov,/vast/projects/exasky/pascal/genesis_model_car...,modelcard.db,/home/pascalgrosset/projects/dsi/dsi_databases...,1,[models]

In [5]:
federated_dbs.f_search_for_databases(original_location="darwin")

,id,original_location,original_path,name,path,num_tables,tables
5,5,darwin-fe.lanl.gov,/vast/projects/exasky/pascal/genesis_model_car...,modelcard.db,/home/pascalgrosset/projects/dsi/dsi_databases...,1,[models]

In [6]:
federated_dbs.f_search_for_databases(name="ocean_11_datasets")

,id,original_location,original_path,name,path,num_tables,tables
2,2,local,/home/pascalgrosset/projects/dsi/tools/federat...,ocean_11_datasets.db,/home/pascalgrosset/projects/dsi/tools/federat...,1,[genesis_datacard]
4,4,github,https://github.com/lanl/dsi/tree/ai_dev/tools/...,ocean_11_datasets.db,/home/pascalgrosset/projects/dsi/dsi_databases...,1,[genesis_datacard]

In [7]:
federated_dbs.f_summary(db="nif.db")

[[       column     type unique   min   max   avg std_dev
  0  array_name  VARCHAR      9  None  None  None    None
  1  array_type  VARCHAR      1  None  None  None    None,
          column     type unique            min                max  \
  0     sim_name  VARCHAR     20           None               None
  1     timestep      INT     20           None               None
  2   num_arrays      INT      1           None               None
  3        shape  VARCHAR     19           None               None
  4     ablt_min    FLOAT      1            0.0                0.0
  5     ablt_max    FLOAT      1            1.0                1.0
  6     cham_min    FLOAT      1            0.0                0.0
  7     cham_max    FLOAT      1            1.0                1.0
  8     dens_min    FLOAT     17       0.000007           0.000017
  9     dens_max    FLOAT     20        2.63112           7.954777
  10    depo_min    FLOAT      1            0.0                0.0
  11    depo_max    FLOAT      7            0.0  631241946693632.0
  12    foam_min    FLOAT      1            0.0                0.0
  13    foam_max    FLOAT      1            1.0                1.0
  14    mark_min    FLOAT      1            0.0                0.0
  15    mark_max    FLOAT     15       0.869509                1.0
  16    pres_min    FLOAT     13   64537.273438        145610080.0
  17    pres_max    FLOAT     20  13322898432.0   49812749680640.0
  18    tele_min    FLOAT      7          100.0         290.113739
  19    tele_max    FLOAT     20     290.113739         25568906.0
  20    tion_min    FLOAT     20     100.015419         290.113739
  21    tion_max    FLOAT     20     290.113739        204943472.0
  22        link  VARCHAR     20           None               None

                         avg                std_dev
  0                     None                   None
  1                     None                   None
  2                     None                   None
  3                     None                   None
  4                      0.0                    0.0
  5                      1.0                    0.0
  6                      0.0                    0.0
  7                      1.0                    0.0
  8                 0.000011               0.000002
  9                  3.88577               1.558216
  10                     0.0                    0.0
  11  106290742506291.203125  181199799421100.90625
  12                     0.0                    0.0
  13                     1.0                    0.0
  14                     0.0                    0.0
  15                0.919135               0.059895
  16         57835229.434375         70132642.41406
  17        18564424398592.0  16284464792187.894531
  18              115.426267              43.319846
  19         10686004.230687         9488240.932297
  20              201.458951              53.509086
  21         38515589.955687        57459705.183758
  22                    None                   None  ],
 [       column     type unique   min   max   avg std_dev
  0  array_name  VARCHAR      9  None  None  None    None
  1  array_type  VARCHAR      1  None  None  None    None,
          column     type unique            min                max  \
  0     sim_name  VARCHAR     20           None               None
  1     timestep      INT     20           None               None
  2   num_arrays      INT      1           None               None
  3        shape  VARCHAR     19           None               None
  4     ablt_min    FLOAT      1            0.0                0.0
  5     ablt_max    FLOAT      1            1.0                1.0
  6     cham_min    FLOAT      1            0.0                0.0
  7     cham_max    FLOAT      1            1.0                1.0
  8     dens_min    FLOAT     17       0.000007           0.000017
  9     dens_max    FLOAT     20        2.63112           7.954777
  10    depo_min    FLOAT      1            0.0                0.0
  11    depo_max    FLOAT      7            0.0  631241946693632.0
  12    foam_min    FLOAT      1            0.0                0.0
  13    foam_max    FLOAT      1            1.0                1.0
  14    mark_min    FLOAT      1            0.0                0.0
  15    mark_max    FLOAT     15       0.869509                1.0
  16    pres_min    FLOAT     13   64537.273438        145610080.0
  17    pres_max    FLOAT     20  13322898432.0   49812749680640.0
  18    tele_min    FLOAT      7          100.0         290.113739
  19    tele_max    FLOAT     20     290.113739         25568906.0
  20    tion_min    FLOAT     20     100.015419         290.113739
  21    tion_max    FLOAT     20     290.113739        204943472.0
  22        link  VARCHAR     20           None               None

                         avg                std_dev
  0                     None                   None
  1                     None                   None
  2                     None                   None
  3                     None                   None
  4                      0.0                    0.0
  5                      1.0                    0.0
  6                      0.0                    0.0
  7                      1.0                    0.0
  8                 0.000011               0.000002
  9                  3.88577               1.558216
  10                     0.0                    0.0
  11  106290742506291.203125  181199799421100.90625
  12                     0.0                    0.0
  13                     1.0                    0.0
  14                     0.0                    0.0
  15                0.919135               0.059895
  16         57835229.434375         70132642.41406
  17        18564424398592.0  16284464792187.894531
  18              115.426267              43.319846
  19         10686004.230687         9488240.932297
  20              201.458951              53.509086
  21         38515589.955687        57459705.183758
  22                    None                   None  ]]

In [13]:
federated_dbs.f_find(query="dens_max > 5", db="nif.db")

Finding all rows where 'dens_max > 5' in the active backend
Finding all rows where 'dens_max > 5' in the active backend

[                      sim_name  timestep  num_arrays               shape  \
 0  nifcylxyz_hdf5_plt_cnt_0005         5           9  (8664, 16, 16, 16)
 1  nifcylxyz_hdf5_plt_cnt_0007         7           9  (8304, 16, 16, 16)
 2  nifcylxyz_hdf5_plt_cnt_0006         6           9  (8408, 16, 16, 16)
 3  nifcylxyz_hdf5_plt_cnt_0008         8           9  (8496, 16, 16, 16)

    ablt_min  ablt_max  cham_min  cham_max  dens_min  dens_max  ...  foam_max  \
 0       0.0       1.0       0.0       1.0  0.000009  5.666894  ...       1.0
 1       0.0       1.0       0.0       1.0  0.000010  7.381287  ...       1.0
 2       0.0       1.0       0.0       1.0  0.000010  7.954777  ...       1.0
 3       0.0       1.0       0.0       1.0  0.000010  5.255617  ...       1.0

    mark_min  mark_max     pres_min      pres_max   tele_min    tele_max  \
 0       0.0  1.000000  65130.90625  3.425035e+13  100.00000  23783628.0
 1       0.0  0.910547  65130.90625  3.571370e+13  100.00000  15957877.0
 2       0.0  0.999962  65130.90625  4.037818e+13  156.77063  23426554.0
 3       0.0  0.874049  65130.90625  2.591218e+13  100.00000  11094333.0

      tion_min    tion_max                                               link
 0  148.416901  81353384.0  https://oceans11.lanl.gov/nif/N210201-001_3D_r...
 1  202.622498  46893368.0  https://oceans11.lanl.gov/nif/N210201-001_3D_r...
 2  156.770630  50003680.0  https://oceans11.lanl.gov/nif/N210201-001_3D_r...
 3  204.019913  11615710.0  https://oceans11.lanl.gov/nif/N210201-001_3D_r...

 [4 rows x 23 columns],
                       sim_name  timestep  num_arrays               shape  \
 0  nifcylxyz_hdf5_plt_cnt_0005         5           9  (8664, 16, 16, 16)
 1  nifcylxyz_hdf5_plt_cnt_0007         7           9  (8304, 16, 16, 16)
 2  nifcylxyz_hdf5_plt_cnt_0006         6           9  (8408, 16, 16, 16)
 3  nifcylxyz_hdf5_plt_cnt_0008         8           9  (8496, 16, 16, 16)

    ablt_min  ablt_max  cham_min  cham_max  dens_min  dens_max  ...  foam_max  \
 0       0.0       1.0       0.0       1.0  0.000009  5.666894  ...       1.0
 1       0.0       1.0       0.0       1.0  0.000010  7.381287  ...       1.0
 2       0.0       1.0       0.0       1.0  0.000010  7.954777  ...       1.0
 3       0.0       1.0       0.0       1.0  0.000010  5.255617  ...       1.0

    mark_min  mark_max     pres_min      pres_max   tele_min    tele_max  \
 0       0.0  1.000000  65130.90625  3.425035e+13  100.00000  23783628.0
 1       0.0  0.910547  65130.90625  3.571370e+13  100.00000  15957877.0
 2       0.0  0.999962  65130.90625  4.037818e+13  156.77063  23426554.0
 3       0.0  0.874049  65130.90625  2.591218e+13  100.00000  11094333.0

      tion_min    tion_max                                               link
 0  148.416901  81353384.0  https://oceans11.lanl.gov/nif/N210201-001_3D_r...
 1  202.622498  46893368.0  https://oceans11.lanl.gov/nif/N210201-001_3D_r...
 2  156.770630  50003680.0  https://oceans11.lanl.gov/nif/N210201-001_3D_r...
 3  204.019913  11615710.0  https://oceans11.lanl.gov/nif/N210201-001_3D_r...

 [4 rows x 23 columns]]

In [9]:
x = federated_dbs._find_db_path(db="nif.db")