In [1]:
from dsi.dsi import DSI
from pathlib import Path
import pandas as pd
from pandasql import sqldf

In [8]:
help(DSI)

Help on class DSI in module dsi.dsi:

class DSI(builtins.object)
 |  DSI(filename='.temp_dsi.db', backend_name='Sqlite', **kwargs)
 |
 |  A user-facing interface for DSI's Core middleware.
 |
 |  The DSI Class abstracts Core.Terminal for managing metadata and Core.Sync for data management and movement.
 |
 |  Methods defined here:
 |
 |  __init__(self, filename='.temp_dsi.db', backend_name='Sqlite', **kwargs)
 |      Initializes DSI by activating a backend for data operations; default is a Sqlite backend for temporary data analysis.
 |      If users specify `filename`, data is saved to a permanent backend file.
 |      Can now call read(), find(), update(), query(), write() or any backend printing operations
 |
 |      `filename` : str, optional
 |          If not specified, a temporary, hidden backend file is created for users to analyze their data.
 |          If specified and backend file already exists, it is activated for a user to explore its data.
 |          If specified and backend file does not exist, a file with this name is created.
 |
 |          Accepted file extensions:
 |              - If backend_name = "Sqlite" → .db, .sqlite, .sqlite3
 |              - If backend_name = "DuckDB" → .duckdb, .db
 |
 |      `backend_name` : str, optional
 |          Name of the backend to activate. Must be either "Sqlite" or "DuckDB".
 |          Default is "Sqlite".
 |
 |  close(self)
 |      Closes the connection to the active backend and clears all loaded DSI modules.
 |
 |  display(self, table_name, num_rows=25, display_cols=None)
 |      Prints data from a specified table in the active backend.
 |
 |      `table_name` : str
 |          Name of the table to display.
 |
 |      `num_rows` : int, optional, default=25
 |          Maximum number of rows to print. If the table contains fewer rows, only those are shown.
 |
 |      `display_cols` : list of str, optional
 |          List of specific column names to display from the table.
 |
 |          If None (default), all columns are displayed.
 |
 |  fetch(self, fname)
 |
 |  find(self, query, collection=False, update=False)
 |      Finds all rows in the table where a column-level condition (e.g., "age > 4") is satisfied.
 |
 |      `query` : str
 |          A column-level condition that must be in the format of a [column name] [operator] [value].
 |          The value can be a string or number. Valid operators as example queries:
 |
 |          - age > 4
 |          - age < 4
 |          - age >= 4
 |          - age <= 4
 |          - age = 4
 |          - age == 4
 |          - age ~ 4    --> column age contains the number 4
 |          - age ~~ 4   --> column age contains the number 4
 |          - age != 4
 |          - age (4, 8) --> all values in 'age' between 4 and 8 (inclusive)
 |
 |      `collection` : bool, optional, default False.
 |          If True, returns a pandas DataFrame representing a subset of table rows that satisfy the `query`.
 |
 |          If False (default), prints the result.
 |
 |      `update` : bool, optional, default False.
 |          If True, includes 'dsi_table_name' and 'dsi_row_index' columns required for ``dsi.update()``.
 |
 |          If False (default), return object does not include these columns.
 |
 |      `return` : If there are no matches found, then nothing is returned or printed
 |
 |  get(self, dbname)
 |      #help, edge-finding (find this/that)
 |
 |  get_table(self, table_name, collection=False, update=False)
 |      Retrieves all data from a specified table without requiring knowledge of the active backend's query language.
 |
 |      This method offers a simplified alternative to `query()` for retrieving a full table data without using SQL.
 |
 |      `table_name` : str
 |          Name of the table from which all data will be retrieved.
 |
 |      `collection` : bool, optional, default False.
 |          If True, returns the result as a pandas DataFrame.
 |
 |          If False (default), prints the result.
 |
 |      `update` : bool, optional, default False.
 |          If True, includes a 'dsi_table_name' column required for ``dsi.update()``.
 |
 |          If False (default), return object does not include this column.
 |
 |      `return`: If `table_name` does not exist in the backend, then nothing is returned or printed
 |
 |  list(self, collection: bool = False) -> list | None
 |      Gets the names and dimensions (rows x columns) of all tables in the active backend.
 |
 |      Arguments:
 |          collection (bool): If True, returns a Python list of all the table names else if False (default), prints each table's name and dimensions to the console.
 |
 |      Returns:
 |          list | None : list of table names if collection is True, else None. If there are no tables in the backend, then nothing is returned or printed.
 |
 |      Raises:
 |          ValueError: If backend is empty or invalid.
 |          RuntimeError: If called before schema data is loaded or if listing fails.
 |
 |  list_backends(self)
 |      Prints a list of valid backends that can be used in the `backend_name` argument in `backend()`
 |
 |  list_readers(self)
 |      Prints a list of valid readers that can be used in the `reader_name` argument in `read()`
 |
 |  list_writers(self)
 |      Prints a list of valid writers that can be used in the `writer_name` argument in `write()`
 |
 |  move(self, filepath)
 |
 |  num_tables(self)
 |      Prints the number of tables in the active backend.
 |
 |  query(self, statement, collection=False, update=False)
 |      Executes a SQL query on the active backend.
 |
 |      `statement` : str
 |          A SQL query to execute. Only `SELECT` and `PRAGMA` statements are allowed.
 |
 |      `collection` : bool, optional, default False.
 |          If True, returns the result as a pandas DataFrame.
 |
 |          If False (default), prints the result.
 |
 |      `update` : bool, optional, default False.
 |          If True, includes a 'dsi_table_name' column required for ``dsi.update()``.
 |
 |          If False (default), return object does not include this column.
 |
 |      `return`: If the `statement` is incorrectly formatted, then nothing is returned or printed
 |
 |  read(self, filenames, reader_name, table_name=None)
 |      Loads data into DSI using the specified parameter `reader_name`
 |
 |      `filenames` : str or list of str or data object
 |          Either file path(s) to the data file(s) or an in-memory data object.
 |
 |          The expected input type depends on the selected `reader_name`:
 |              - "Collection"           → Ordered Dictionary of table(s)
 |              - "CSV"                  → .csv
 |              - "Parquet"              → .pq
 |              - "YAML1"                → .yaml or .yml
 |              - "TOML1"                → .toml
 |              - "JSON"                 → .json
 |              - "Ensemble"             → .csv
 |              - "Cloverleaf"           → /path/to/data/directory/
 |              - "Bueno"                → .data
 |              - "DublinCoreDatacard"   → .xml
 |              - "SchemaOrgDatacard"    → .json
 |              - "GoogleDatacard"       → .yaml or .yml
 |              - "Oceans11Datacard"     → .yaml or .yml
 |              - "GenesisDatacard"      → .csv
 |
 |      `reader_name` : str
 |          Name of the DSI Reader to use for loading the data.
 |
 |          If using a DSI-supported Reader, this should be one of the reader_names from `list_readers()`.
 |
 |          If using a custom Reader, provide the relative file path to the Python script with the Reader.
 |          For guidance on creating a DSI-compatible Reader, view :ref:`custom_reader`.
 |
 |      `table_name` : str, optional
 |          Name to assign to the loaded table.
 |
 |          Required when using the `Collection` reader to load an Ordered Dictionary representing only one table.
 |
 |          Recommended when the input file contains a single table for the `CSV`, `Parquet`, `JSON`, or `Ensemble` reader.
 |
 |  schema(self, filename=None)
 |      Either loads a relational database schema into DSI with a specified `filename` OR returns this database's structural schema.
 |
 |      `filename` : str, optional
 |          Path to a JSON file describing the relationships of the tables in a database.
 |          The schema should follow the format described in :ref:`user_schema_example_label`
 |
 |      `return` : If filename = None, returns the structural schema of this database - table/col names and their units.
 |      **If loading a relational schema, this function must be called before reading in any associated data files**
 |
 |  search(self, query, collection=False)
 |      Finds all rows across all tables in the active backend where `query` can be found.
 |
 |      `query` : int, float, or str
 |          The value to search for in all rows across all tables.
 |
 |      `collection` : bool, optional, default False.
 |          If True, returns a list of pandas DataFrames representing a subset of tables where `query` is found.
 |
 |          If False (default), prints the matches to the console.
 |
 |  summary(self, table_name=None, collection=False)
 |      Prints numerical metadata and (optionally) sample data from tables in the active backend.
 |
 |      `table_name` : str, optional
 |          If specified, only the numerical metadata for that table will be printed.
 |
 |          If None (default), metadata for all available tables is printed.
 |
 |      `collection` : bool, optional, default False.
 |          If True, and table_name specified, returns a Pandas DataFrame of the summary of that table.
 |
 |          If True, and table_name not specified, returns a list of Pandas DataFrames of the summary of all tables.
 |
 |          If False (default), prints each table's name and dimensions to the console.
 |
 |  update(self, collection, backup=False)
 |      Updates data in one or more tables in the active backend using the provided input.
 |      Intended to be used after modifying the output of `find()`, `search()`, `query()`, or `get_table()`
 |
 |      `collection` : pandas.DataFrame
 |          The data used to update a table.
 |          DataFrame must include unchanged **`dsi_`** columns from `find()`, `search()`, `query()` or `get_table()` to successfully update.
 |
 |          - If a `query()` DataFrame is the input, the corresponding table in the backend will be completely overwritten.
 |
 |      `backup` : bool, optional, default False.
 |          If True, creates a backup file for the DSI backend before updating its data.
 |
 |          If False (default), only updates the data.
 |
 |      - NOTE: Columns from the original table cannot be deleted during update. Only row edits or column additions are allowed.
 |      - NOTE: If update() affects a user-defined primary key column, row order may change upon reinsertion.
 |
 |  write(self, filename, writer_name, table_name=None)
 |      Exports data from the active backend using the specified `writer_name`.
 |
 |      `filename` : str
 |          Name of the output file to write.
 |
 |          Expected file extensions based on `writer_name`:
 |              - "ER_Diagram"   → .png, .pdf, .jpg, .jpeg
 |              - "Table_Plot"   → .png, .jpg, .jpeg
 |              - "Csv"          → .csv
 |              - "Parquet"      → .pq
 |
 |      `writer_name` : str
 |          Name of the DSI Writer to export data.
 |
 |          If using a DSI-supported Writer, this should be one of the writer_names from `list_writers()`.
 |
 |          If using a custom Writer, provide the relative file path to the Python script with the Writer.
 |          For guidance on creating a DSI-compatible Writer, view :ref:`custom_writer`.
 |
 |      `table_name`: str, optional
 |          Required when using "Table_Plot", "Csv" or "Parquet" to specify which table to export.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  __dict__
 |      dictionary for instance variables
 |
 |  __weakref__
 |      list of weak references to the object

In [84]:
class f_dsi:
    def __init__(self, folder_name:str):
        self.folder_name = folder_name
        folder = Path(folder_name)
        db_path_list = []
        for p in folder.iterdir():
            if p.is_file():
                db_path_list.append(p)
        
        databases = []
        for d_id, db_path in enumerate(db_path_list):
            db_info = {}
            try:
                _temp = DSI(str(db_path), silence_messages="True")
                db_info['id'] = d_id
                db_info['path'] = str(db_path)
                db_info['name'] = (str(db_path)).split('/')[-1]
                _tbls = _temp.list(True)
                db_info['num_tables'] = len(_tbls)
                db_info['tables'] = _tbls
                
                _temp.close()
                
                databases.append(db_info)
            except Exception as e:
                print(f"Error {e} opening database at {db_path}!")
    
        self.df = f_collect_databases(folder_name)
        self.df_exp = df.explode("tables").rename(columns={"tables": "table"})

        
    def f_get_databases(self):
        return self.df
    
    def f_summarize(self, table, db):
        q = f"SELECT path FROM df_exp WHERE \"table\" = '{table}' AND name = '{db}'"
        print(q)
        
        out = sqldf(q, {"df_exp": self.df_exp})
        path_str = out.loc[0, "path"]
        print(path_str)
    
        _temp = DSI(path_str, silence_messages="True")
        l = _temp.summary(collection=True)
        return l


    def f_query(self, table, db, query):
        q = f"SELECT path FROM df_exp WHERE \"table\" = '{table}' AND name = '{db}'"
        print(q)
        
        out = sqldf(q, {"df_exp": self.df_exp})
        path_str = out.loc[0, "path"]
    
        _temp = DSI(path_str, silence_messages="True")
        l = _temp.query(query, collection=True)
        return l

    def f_search(self, table, db, query):
        q = f"SELECT path FROM df_exp WHERE \"table\" = '{table}' AND name = '{db}'"
        print(q)
        
        out = sqldf(q, {"df_exp": self.df_exp})
        path_str = out.loc[0, "path"]
    
        _temp = DSI(path_str, silence_messages="True")
        l = _temp.search(query, collection=True)
        return l

    def f_find(self, table, db, query):
        q = f"SELECT path FROM df_exp WHERE \"table\" = '{table}' AND name = '{db}'"
        print(q)
        
        out = sqldf(q, {"df_exp": self.df_exp})
        path_str = out.loc[0, "path"]
    
        _temp = DSI(path_str, silence_messages="True")
        l = _temp.find(query, collection=True)
        return l

(venv_dsi) pascalgrosset@PN2608148:~/projects/dsi$ python tools/federated/test_federation.py tools/federated/input.yaml
Created: /home/pascalgrosset/projects/dsi/_workspace_9f7b4fd4

 - Processing database at github:github:https://github.com/lanl/dsi/tree/ai_dev/tools/ai_search/data/oceans_11/ocean_11_datasets.db

 - Processing database at HPC:darwin-fe.lanl.gov:/users/pulido/modelcard2.db
 -- Could not access the file at darwin-fe.lanl.gov:/users/pulido/modelcard2.db. Skipping this database.

 - Processing database at HPC:ch-fe.lanl.gov:/lustre/scratch5/pascalgrosset/test_db/nif.db
(pascalgrosset@ch-fe.lanl.gov) Password:
(pascalgrosset@ch-fe.lanl.gov) Password:
         20,480 100%  246.91kB/s    0:00:00 (xfr#1, to-chk=0/1)

 - Processing database at HPC:darwin-fe.lanl.gov:/vast/projects/exasky/pascal/genesis_model_cards/modelcard.db
      1,093,632 100%    3.82MB/s    0:00:00 (xfr#1, to-chk=0/1)

Finished gathering databases. Successfully downloaded 3 files to _workspace_9f7b4fd4.

In [93]:
folder_name = "/home/pascalgrosset/projects/dsi/tools/federated/_workspace_9f7b4fd4/"

In [94]:
x = f_dsi(folder_name)

In [95]:
df = x.f_get_databases()
df

,id,path,name,num_tables,tables
0,0,/home/pascalgrosset/projects/dsi/tools/federat...,modelcard.db,1,[models]
1,1,/home/pascalgrosset/projects/dsi/tools/federat...,ocean_11_datasets.db,1,[genesis_datacard]
2,2,/home/pascalgrosset/projects/dsi/tools/federat...,nif.db,2,"[array_and_types, nif_metadata]"

In [87]:
 x.f_summarize(table="nif_metadata", db="nif.db")

SELECT path FROM df_exp WHERE "table" = 'nif_metadata' AND name = 'nif.db'
/home/pascalgrosset/projects/dsi/tools/federated/_workspace_9f7b4fd4/nif.db

[       column     type unique   min   max   avg std_dev
 0  array_name  VARCHAR      9  None  None  None    None
 1  array_type  VARCHAR      1  None  None  None    None,
         column     type unique            min                max  \
 0     sim_name  VARCHAR     20           None               None
 1     timestep      INT     20           None               None
 2   num_arrays      INT      1           None               None
 3        shape  VARCHAR     19           None               None
 4     ablt_min    FLOAT      1            0.0                0.0
 5     ablt_max    FLOAT      1            1.0                1.0
 6     cham_min    FLOAT      1            0.0                0.0
 7     cham_max    FLOAT      1            1.0                1.0
 8     dens_min    FLOAT     17       0.000007           0.000017
 9     dens_max    FLOAT     20        2.63112           7.954777
 10    depo_min    FLOAT      1            0.0                0.0
 11    depo_max    FLOAT      7            0.0  631241946693632.0
 12    foam_min    FLOAT      1            0.0                0.0
 13    foam_max    FLOAT      1            1.0                1.0
 14    mark_min    FLOAT      1            0.0                0.0
 15    mark_max    FLOAT     15       0.869509                1.0
 16    pres_min    FLOAT     13   64537.273438        145610080.0
 17    pres_max    FLOAT     20  13322898432.0   49812749680640.0
 18    tele_min    FLOAT      7          100.0         290.113739
 19    tele_max    FLOAT     20     290.113739         25568906.0
 20    tion_min    FLOAT     20     100.015419         290.113739
 21    tion_max    FLOAT     20     290.113739        204943472.0
 22        link  VARCHAR     20           None               None

                        avg                std_dev
 0                     None                   None
 1                     None                   None
 2                     None                   None
 3                     None                   None
 4                      0.0                    0.0
 5                      1.0                    0.0
 6                      0.0                    0.0
 7                      1.0                    0.0
 8                 0.000011               0.000002
 9                  3.88577               1.558216
 10                     0.0                    0.0
 11  106290742506291.203125  181199799421100.90625
 12                     0.0                    0.0
 13                     1.0                    0.0
 14                     0.0                    0.0
 15                0.919135               0.059895
 16         57835229.434375         70132642.41406
 17        18564424398592.0  16284464792187.894531
 18              115.426267              43.319846
 19         10686004.230687         9488240.932297
 20              201.458951              53.509086
 21         38515589.955687        57459705.183758
 22                    None                   None  ]

In [89]:
x.f_find(table="nif_metadata", db="nif.db", query="dens_max > 5")

SELECT path FROM df_exp WHERE "table" = 'nif_metadata' AND name = 'nif.db'
Finding all rows where 'dens_max > 5' in the active backend

,sim_name,timestep,num_arrays,shape,ablt_min,ablt_max,cham_min,cham_max,dens_min,dens_max,...,foam_max,mark_min,mark_max,pres_min,pres_max,tele_min,tele_max,tion_min,tion_max,link
0,nifcylxyz_hdf5_plt_cnt_0005,5,9,"(8664, 16, 16, 16)",0.0,1.0,0.0,1.0,0.000009,5.666894,...,1.0,0.0,1.000000,65130.90625,3.425035e+13,100.00000,23783628.0,148.416901,81353384.0,https://oceans11.lanl.gov/nif/N210201-001_3D_r...
1,nifcylxyz_hdf5_plt_cnt_0007,7,9,"(8304, 16, 16, 16)",0.0,1.0,0.0,1.0,0.000010,7.381287,...,1.0,0.0,0.910547,65130.90625,3.571370e+13,100.00000,15957877.0,202.622498,46893368.0,https://oceans11.lanl.gov/nif/N210201-001_3D_r...
2,nifcylxyz_hdf5_plt_cnt_0006,6,9,"(8408, 16, 16, 16)",0.0,1.0,0.0,1.0,0.000010,7.954777,...,1.0,0.0,0.999962,65130.90625,4.037818e+13,156.77063,23426554.0,156.770630,50003680.0,https://oceans11.lanl.gov/nif/N210201-001_3D_r...
3,nifcylxyz_hdf5_plt_cnt_0008,8,9,"(8496, 16, 16, 16)",0.0,1.0,0.0,1.0,0.000010,5.255617,...,1.0,0.0,0.874049,65130.90625,2.591218e+13,100.00000,11094333.0,204.019913,11615710.0,https://oceans11.lanl.gov/nif/N210201-001_3D_r...